const routes = require('express').Router();
const userControllers = require('../db/controllers/userCtrl.js');
const s3Controller = require('../db/controllers/s3Ctrl.js');
const challengeController = require('../db/controllers/challengeCtrl.js');
const commentController = require('../db/controllers/commentCtrl.js');
const followerController = require('../db/controllers/followerCtrl.js');

routes.post('/signup', userControllers.signup);
routes.post('/login', userControllers.login);
routes.get('/logout', userControllers.logout);
routes.get('/profile/:username', userControllers.getUser);
routes.get('/profile', userControllers.getUser);
routes.put('/profile', userControllers.updateProfile);
routes.get('/ranks', userControllers.getAllUsers);
routes.post('/userUpload', s3Controller);
routes.post('/s3', challengeController.s3);
routes.post('/challenge', challengeController.addOne);
routes.get('/allChallenges', challengeController.getAll);
routes.get('/challenge/:id', challengeController.getOne);
routes.put('/challenge/:id', challengeController.updateOne);
routes.delete('/challenge/:id', challengeController.deleteOne);
routes.post('/response', challengeController.addOneResponse);
routes.get('/response', challengeController.getAllResponses);
routes.post('/comments', commentController.addOne);
routes.get('/comments', commentController.getAll);
routes.post('/upvote', challengeController.upvote);
routes.post('/viewed', challengeController.viewed);
routes.post('/unFollow', followerController.unFollow);
routes.post('/follower', followerController.follow);
routes.get('/getLeaders', followerController.getLeaders);
routes.get('/listFollowers', followerController.getListOfFollowers);
routes.post('/favorite', challengeController.favorite);
routes.get('/favorite', challengeController.getFavorites);
routes.post('/unFavorite', challengeController.unFavorite);

module.exports = routes;